In [3]:
!pip install pandas 
!pip install numpy

import pandas as pd
import numpy as np


[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: C:\Users\Dell\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip



[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: C:\Users\Dell\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip


In [8]:
# Exercise #2 (page 40): Using Numpy Statistical Functions

# Base Salary
sam_salary = [25000, 27000, 24000]
joe_salary = [31000, 29000, 30000]
kate_salary = [35000, 31000, 25000]
larry_salary = [20000, 24000, 27000]

base_salary = np.array([sam_salary, joe_salary, kate_salary, larry_salary])

# Bonus
sam_bonus = [3000, 4000, 4000]
joe_bonus = [1000, 9000, 2000]
kate_bonus = [8000, 3000, 5000]
larry_bonus = [6000, 4000, 7000]

bonus = np.array([sam_bonus, joe_bonus, kate_bonus, larry_bonus])

print("Base Salary: \n", base_salary)
print("Bonus: \n", bonus)
print("Base + Bonus: \n", base_salary + bonus)

Base Salary: 
 [[25000 27000 24000]
 [31000 29000 30000]
 [35000 31000 25000]
 [20000 24000 27000]]
Bonus: 
 [[3000 4000 4000]
 [1000 9000 2000]
 [8000 3000 5000]
 [6000 4000 7000]]
Base + Bonus: 
 [[28000 31000 28000]
 [32000 38000 32000]
 [43000 34000 30000]
 [26000 28000 34000]]


In [23]:
total_salary = base_salary + bonus

print("Highest: ", total_salary.max())
print("Lowest:  ", total_salary.min())
print("Average: ", np.average(total_salary))
print("Median:  ", np.median(total_salary))

print("Highest(Row/Each Employee): \n", np.amax(total_salary, axis=1))
print("Highest(Column/Each Month): \n", np.amax(total_salary, axis=0))

Highest:  43000
Lowest:   26000
Average:  32000.0
Median:   31500.0
Highest(Row/Each Employee): 
 [31000 38000 43000 34000]
Highest(Column/Each Month): 
 [43000 38000 34000]


In [34]:
employees = ["Sam Smith", "Joe Craig", "Kate Watson", "Larry Potter"]
employee_names = pd.Series(employees, index = [9000, 9001, 9002, 9003])

# Showing all data
print(employee_names)

# Accessing data in a Series
print(employee_names.loc[9001:9002])
print(employee_names.iloc[1:3])

9000       Sam Smith
9001       Joe Craig
9002     Kate Watson
9003    Larry Potter
dtype: object
9001      Joe Craig
9002    Kate Watson
dtype: object
9001      Joe Craig
9002    Kate Watson
dtype: object
